# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: auth-service
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: auth-service
#   template:
#     metadata:
#       labels:
#         app: auth-service
#     spec:
#       containers:
#         - name: auth-service
#           image: ghcr.io/inholland-cloud-minor-2526/group-7-auth-service/auth-service:latest
#           ports:
#             - containerPort: 8080
#           env:
#             - name: MESSAGE
#               valueFrom:
#                 configMapKeyRef:
#                   name: app-config
#                   key: MESSAGE
