apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: group-7-elias

resources:
  - ../../base

images:
  - name: ghcr.io/inholland-cloud-minor-2526/auth-service
    newTag: latest

replicas:
  - name: auth-service
    count: 2
